name: Realking_kernel_sm8250 Kernel Lmi
run-name: Realking_kernel_sm8250 Kernel Lmi

on:
  push:
    branches: [ rebase ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nexgang/ubuntu:latest
          
    steps:
      - name: Download Proton-Clang
        run: |
          cd $HOME
          mkdir proton-clang
          cd proton-clang
          wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
          unzip 20210522.zip
          
      - uses: actions/checkout@v3
      - name: Nexus Kernel Lmi
        run: bash build_kernel.sh lmi
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
